version: '3.8'
services:
  user_service_db:
    image: mysql:8.0.28
    restart: always
    environment:
      MYSQL_DATABASE: ${USER_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "13306:3306"
    volumes:
      - user_service_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

  activity_service_db:
    image: mysql:8.0.28
    restart: always
    environment:
      MYSQL_DATABASE: ${ACTIVITY_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "13307:3306"
    volumes:
      - activity_service_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

  newsfeed_service_db:
    image: mysql:8.0.28
    restart: always
    environment:
      MYSQL_DATABASE: ${NEWSFEED_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "13308:3306"
    volumes:
      - newsfeed_service_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

volumes:
  user_service_data:
  activity_service_data:
  newsfeed_service_data:
