spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community_commerce_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 5032
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # create none update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

jwt:
  header: Authorization
  secret: StCFPUF/xyPmMs+4ioxso1RQUYm4fWZyaJtcB9OSosK5/z5J76PgaVpahYUwew27hk9aEAPrK6/JN71+OzliEA==
  token-validity-in-seconds: 86400

logging:
  level:
    ROOT: INFO
  path: ./
